# Generated by Django 2.0.13 on 2019-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190407_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
