# Generated by Django 2.0.13 on 2019-04-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20190407_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
