# Generated by Django 2.0.13 on 2019-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20190430_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.IntegerField(),
        ),
    ]
