# Generated by Django 2.0.13 on 2019-05-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20190501_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('age1', models.IntegerField()),
                ('view_count1', models.IntegerField(default=0)),
                ('created_at1', models.DateTimeField(auto_now_add=True)),
                ('updated_at1', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
