# Generated by Django 2.0.13 on 2019-05-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20190501_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player2',
            name='description1',
            field=models.TextField(null=True),
        ),
    ]
