# Generated by Django 2.0.13 on 2019-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20190501_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player2',
            name='age1',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
