# Generated by Django 2.0.13 on 2019-05-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20190505_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
